apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: customer-jvm
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/sash-383710/customer-jvm:v1
          env:
            - name: TARGET
              value: "Spring Boot Sample v1"
